name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get update
      - name: Continue installing
        run: |
          apt-get install -y python3-pip
      - name: Packages
        run: |
          pip3 install pytest
      - name: Run test
        run: |
          pytest
